export const NUMBER_DOWN = "down";
export const NUMBER_RIGHT = "right";
export const EMPTY = "";
export const BLACK_TILE = "black";
export const crosswordValues = [
  [BLACK_TILE, BLACK_TILE, NUMBER_RIGHT, BLACK_TILE, BLACK_TILE, BLACK_TILE, BLACK_TILE, BLACK_TILE], // col 1
  [NUMBER_DOWN, EMPTY, EMPTY, EMPTY, BLACK_TILE, BLACK_TILE, NUMBER_RIGHT, BLACK_TILE], // col 2
  [BLACK_TILE, BLACK_TILE, EMPTY, NUMBER_DOWN, EMPTY, EMPTY, EMPTY, BLACK_TILE], // col 3
  [BLACK_TILE, BLACK_TILE, EMPTY, BLACK_TILE, BLACK_TILE, NUMBER_RIGHT, EMPTY, BLACK_TILE], // col 4
  [BLACK_TILE, NUMBER_DOWN, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, NUMBER_RIGHT], // col 5
  [BLACK_TILE, BLACK_TILE, EMPTY, BLACK_TILE, NUMBER_RIGHT, EMPTY, BLACK_TILE, EMPTY], // col 6
  [NUMBER_DOWN, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY], // col 7
  [BLACK_TILE, BLACK_TILE, EMPTY, BLACK_TILE, EMPTY, BLACK_TILE, BLACK_TILE, BLACK_TILE], // col 8
  [BLACK_TILE, BLACK_TILE, NUMBER_DOWN, EMPTY, EMPTY, EMPTY, EMPTY, BLACK_TILE], // col 9
];

export default {
  NUMBER_DOWN, NUMBER_RIGHT, EMPTY, BLACK_TILE, crosswordValues
}